apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongod
spec:
  serviceName: mongodb-service
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: mongo
        replicaset: rs0
    spec:
      nodeSelector:
        role: mongo
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: secrets-volume
        secret:
          secretName: mongo-certificate
          defaultMode: 256
      containers:
      - name: mongod-container
        image: mongo:4.1.10
        command:
        - "mongod"
        - "--bind_ip"
        - "0.0.0.0"
        - "--replSet"
        - "rs0"
        - "--sslMode"
        - "preferSSL"
        - "--sslAllowConnectionsWithoutCertificates"
        - "--sslPEMKeyFile"
        - "/data/static/combined.pem"
        - "--sslAllowInvalidCertificates"
        ports:
        - name: service-port
          containerPort: 27017
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: secrets-volume
          readOnly: true
          mountPath: /data/static
