apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongod
spec:
  serviceName: mongodb-service
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        replicaset: rs0
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: secrets-volume
        secret:
          secretName: mongo-certificate
          defaultMode: 256
      containers:
      - name: mongod-container
        image: sconecuratedimages/apps:mongodb-3.4.4-alpine
        env:
        - name: SCONE_MODE
          value: "HW"
        - name: SCONE_VERSION
          value: "1"
        command:
        - "mongod"
        - "--bind_ip"
        - "0.0.0.0"
        - "--replSet"
        - "rs0"
        - "--sslMode"
        - "preferSSL"
        - "--sslAllowConnectionsWithoutCertificates"
        - "--sslPEMKeyFile"
        - "/data/static/combined.pem"
        - "--sslAllowInvalidCertificates"
        ports:
        - name: service-port
          containerPort: 27017
        livenessProbe:
          tcpSocket:
            port: service-port
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - name: secrets-volume
          readOnly: true
          mountPath: /data/static
        resources:
          requests:
            intel.com/sgx: 10000
          limits:
            intel.com/sgx: 10000
