apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongod
spec:
  serviceName: mongodb-service
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: mongo
        replicaset: rs0
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "role"
                    operator: In
                    values:
                    - mongo
              topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: secrets-volume
        secret:
          secretName: mongo-certificate
          defaultMode: 256
      containers:
      - name: mongod-container
        image: sebvaucher/anonymbe:0.27-mongodb
        env:
        - name: SCONE_MODE
          value: "HW"
        - name: SCONE_VERSION
          value: "1"
        command:
        - "mongod"
        - "--bind_ip"
        - "0.0.0.0"
        - "--replSet"
        - "rs0"
        - "--sslMode"
        - "preferSSL"
        - "--sslAllowConnectionsWithoutCertificates"
        - "--sslPEMKeyFile"
        - "/data/static/combined.pem"
        - "--sslAllowInvalidCertificates"
        ports:
        - name: service-port
          containerPort: 27017
        livenessProbe:
          exec:
            command:
            - ./tlsping.sh
            - localhost:27017
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - ./tlsping.sh
            - localhost:27017
          initialDelaySeconds: 4
          periodSeconds: 3
        volumeMounts:
        - name: secrets-volume
          readOnly: true
          mountPath: /data/static
        resources:
          requests:
            intel.com/sgx: 10
          limits:
            intel.com/sgx: 10
